name: Test-Ryan
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9148328497540206
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#40546c'
    - '#a69c8a'
    - '#bfb6aa'
    - '#8c2727'
    - '#23355a'
  brandStrength: 0.7719108550809324
  lightness: 0.11730007617734373
  saturation: 0.534181846305728
  rhythmicContrast: 0.09813794656656682
purpose: []
