name: Test-Ryan
favicon: null
layout_spectrum: 0.5977093284018338
typography_spectrum: 0.9148328497540206
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7719108550809324
  lightness: 0.11730007617734373
  saturation: 0.534181846305728
  rhythmicContrast: 0.09813794656656682
purpose: []
